### PR TITLE
strip numbers and symbols before check

### PR DESCRIPTION
**Pull request by paddyduff31**
There is duplicated code that could be moved out however there are 3 password components that have a lot of repeated code so this will be addressed together after the current block of work

### CODE REVIEW

**Review by con-nihr — COMMENTED** [review]
Not sure what the motivation behind this change is. Can you explain?
Numbers and symbols are a normal password component, so it is valid to use them to check against the list.
Why are we using a very small client side list when (I believe) we have a more comprehensive server side check?

**Comment by paddyduff31** [comment]
erverside and client side were essentially doing the same check against a list of common passwords but to be honest a lot of this list didn't make any sense for example all of these were in the list but none of these passwords would have even made it past our bog standard password policy never mind common check.
"123456",
            "12345678",
            "admin",
            "qwerty",
            "letmein",
            "football",
            "iloveyou",
            "admin123",
            "welcome",
            "monkey",
            "abc123",
            "login",
            "passw0rd",
            "password1",
            "123123",
            "trustno1",
            "shadow",
            "master",
            "hello",
            "solo",
            "princess",
            "welcome1",
            "qwertyuiop",
  Managing an exhaustive list which would check against all possible combinations would have been extremely difficult(and quite performant problematic I would imagine?) so I have removed the required attributes handled by AWS already and simply comparing against the common words.  I also could not simply do an includes check as the guidance is 3 random words so if someone uses 3 random words and one of them is football this would fail even though it is probably a good password.
I looked at the https://haveibeenpwned.com/ but this is paid now
Kevin also showed me the solution on JDR but this would have been difficult as we would be managing passwords using it and AWS so it would have been a mess
Happy to implement a different solution if you know a better one?

**Review by con-nihr — COMMENTED** [review]
Do we need the FE check at all? A rejection on the server side should result in the same error.
If we do need the FE check then maintaining two lists is problematic. The FE should retrieve a common list from a BE rest endpoint / static content.

**Comment by paddyduff31** [comment]
Implemented on the FE to save additional api calls when not needed.  Would it be worth returning the password list in the PasswordPolicyTypeResponse when getting the actual password policy?

**Comment by con-nihr** [comment]
> Implemented on the FE to save additional api calls when not needed. Would it be worth returning the password list in the PasswordPolicyTypeResponse when getting the actual password policy?

I wouldn't worry too much about saving the BE calls, that is a minimal overhead.
Good idea about returning it in the policy response as it is certainly could be viewed as part of the 'policy'.

**Comment by paddyduff31** [comment]
I have moved this work to MFA branched work for PEN test retest

**Pull request closed without merging**
